### ISSUE TITLE
Elenco problemi skin Timeless

### ISSUE THREAD

**Issue by lucas992x** [pokemoncentral/wiki-project#94]
Usiamo questa issue per raccogliere tutti i bug/problemi riscontrati con la nuova skin Timeless. Per comodità mettiamo qua l'elenco e spieghiamo ciascuna in un commento separato, con screenshot/link/etc.
- [x] [Tabelle responsive collassate](https://github.com/pokemoncentral/wiki-project/issues/94#issuecomment-704142578) [mobile]
- [x] ~~[Elementi larghi che strabordano](https://github.com/pokemoncentral/wiki-project/issues/94#issuecomment-704356755) [desktop]~~ problema rimasto solo con pochi elementi che spesso sono già problematici di per sé
- [x] ~~[Anteprima non mostra categorie e altre lingue](https://github.com/pokemoncentral/wiki-project/issues/94#issuecomment-707772833)[desktop e mobile]~~ succede solo in `xl`, non è prioritario da sistemare

**Comment by lucas992x** [comment]
## Larghezza non interpretata correttamente [desktop]
Timeless ha una sidebar anche a destra, a differenza di Vector che ha solo quella di sinistra. Sfortunatamente le nostre classi responsive (`*-xl-*`, `*-lg-*` e così via) lavorano come se quella sidebar non ci fosse, quindi da desktop pensano di avere uno schermo `xl` quando in realtà la larghezza effettivamente disponibile è `md`/`lg`, quindi accadono problemi come questo (screen Vector sopra e Timeless sotto):
![scr1 1](https://user-images.githubusercontent.com/38510975/95181981-4b1b5900-07c4-11eb-8e22-91b6eb175ec5.png)
![scr1 2](https://user-images.githubusercontent.com/38510975/95181925-33dc6b80-07c4-11eb-9768-ca4ee2bfd1a0.png)

**Comment by lucas992x** [comment]
## Tabelle responsive collassate [mobile]
Abbiamo in giro per il wiki tabelle collassate, tabelle responsive, tabelle sia collassate che responsive. Sembra che le due cose non possano coesistere: se lo schermo è abbastanza stretto da farla diventare responsive la tabella collassa comunque e non risulta espandibile. Ecco un [esempio](https://wiki.pokemoncentral.it/MT#Elenco_delle_MT):
![scr2 1](https://user-images.githubusercontent.com/38510975/95182744-4dca7e00-07c5-11eb-99d7-e0db1382631e.png)
![scr2 2](https://user-images.githubusercontent.com/38510975/95182749-4e631480-07c5-11eb-8a7a-8ec8dccf859a.png)
C'è un workaround che consiste nel ruotare lo schermo, espandere la tabella e poi ruotarlo nuovamente per vedere la tabella espansa e responsivizzata (ma ovviamente non è una soluzione)
![scr2 3](https://user-images.githubusercontent.com/38510975/95182751-4efbab00-07c5-11eb-8692-6198ab58530e.png)

**Comment by flavio-a** [comment]
@lucas992x idea stupida: mettere le tabelle responsive dentro ad un div collassabile invece di rendere le tabelle direttamente collassabili?

**Comment by lucas992x** [comment]
Come rimedio temporaneo ci sta, ma sarebbe auspicabile una soluzione, non sapendo quante tabelle del genere ci sono in giro per il wiki

**Comment by Cruifer** [comment]
succede che quando le tabelle sono troppo larghe queste strabordano e occupano il menu laterale a destra.
![wiki pokemoncentral it-Mosseerratedeigiochi-PokémonCentralWiki](https://user-images.githubusercontent.com/38588039/95223751-38237b80-07fa-11eb-957d-fef3a35c786f.png)

probabilmente succede con poche tabelle non aggiornate, ma comunque c'è

**Comment by CiaobyDany** [comment]
Aggiungo anche che su schermi grandi ma non troppo, possono esserci problemi nella visualizzazione delle notifiche che necessitano di scrolling orizzontale. Non è un vero problema, ovviamente, ma è sintomatico del fatto che qualcosa non funzioni.
![immagine](https://user-images.githubusercontent.com/38566659/95260040-5b651f80-0828-11eb-9f03-f5c44f6ddffb.png)

È già stato fatto presente che il testo sembra ridicolmente enorme? Per avere delle proporzioni simili a Vector devo dezoomare a 90/80% tipo. E a quel punto diverse cose buffe vanno a posto imo.

**Comment by Cruifer** [comment]
cosa buffa che ho notato: 
![image](https://user-images.githubusercontent.com/38588039/95259881-26f16380-0828-11eb-96d4-304ee68fb3bc.png)
in sostanza il div con `position: fixed` straborda la colonna di contenuto. La causa di fondo credo sia la stessa che non fa funzionare i breakpoint correttamente, è come se i breakpoint venissero calcolati con la larghezza di tutte e tre le colonne insieme ma poi effettivamente i contenuti sono in una sola colonna e quindi più stretti. La verità è che non ci ho capito nulla probabilmente, ma mi ha fatto molto ridere la mia pagina utente così

**Comment by CiaobyDany** [comment]
Ragazzi, mi ero dimenticato di farlo presente fino adesso, ma... I breakpoint e i position fixed considerano sempre la dimensione finestra/schermo e non quella del contenuto. È il motivo per cui non si possono fare delle anteprime sensate su Vector di simulazione schermi piccoli perché c'è di mezzo la sidebar. E, ovviamente, se si mette su Vector un position fixed left le cose vanno sulla sidebar. Che è poi il motivo per cui il position fixed l'abbiamo sempre messo a destra e non a sinistra.
![immagine](https://user-images.githubusercontent.com/38566659/95261505-cd3e6880-082a-11eb-9e4a-30192e2f9c9d.png)
(comunque siamo d'accordo che la nuova Vector fa schifo e che non ha senso mettere il nome del sito così togliendo il logo?)

**Comment by lucas992x** [comment]
> Ragazzi, mi ero dimenticato di farlo presente fino adesso, ma... I breakpoint e i position fixed considerano sempre la dimensione finestra/schermo e non quella del contenuto.

E questo è un grossissimo problema, perché con Vector il contenuto è 1.5 volte più largo di quello di Timeless, quindi 1) dovremmo rifare mezzo sito per sistemare tutti questi problemi, e 2) sarebbe comunque un casino immane: in `xl` e `lg` una cosa che va bene con Vector probabilmente risulterà troppo stretta in Timeless mentre una buona in Timeless sarà enorme in Vector. Abbiamo già appurato che succede con gli infobox, ma sicuramente lo fa anche con tante altre cose, e penso che siamo tutti d'accordo sul fatto che sarebbe meglio trovare una soluzione piuttosto che mettersi a rifare mezzo sito con risultati nemmeno buoni.

> È già stato fatto presente che il testo sembra ridicolmente enorme? Per avere delle proporzioni simili a Vector devo dezoomare a 90/80% tipo. E a quel punto diverse cose buffe vanno a posto imo.

Quindi non era solo una mia impressione. In effetti sembra che a 80% diverse cose vadano decisamente meglio, si può impostare così di default in qualche modo?

**Comment by mexicat** [comment]
Il problema della dimensione del testo è dovuto al `font-size: 17px` che c'è sul body nei CSS; andrebbe messo solo su Vector (anche su Minerva si può evitare)

**Comment by lucas992x** [comment]
@mexicat cambiare questa impostazione è fattibile in modo indolore (o quasi) oppure ci sono delle controindicazioni?

**Comment by mexicat** [comment]
Secondo me si può fare tranquillamente, verificando appunto che alla fine `font-size: 17px` compaia solo su Vector

**Comment by flavio-a** [comment]
Allora: non ho idea del perché esista quella impostazione (qualcuno ci vedeva male e voleva aumentare lo zoom del sito?), comunque Vector e Minerva di default hanno `font-size: 16px`, mentre Timeless `font-size:15.2`. Questa potrebbe essere la causa di un po' di problemi.
Sistemare si può sistemare, nel senso che si può mettere la proprietà solo su una certa skin (mettono una `class` sul `body`, quindi basta selezionare le classi della/e skin che ci interessa/no). Io intanto posso sistemare facilmente questa cosa sulla Timeless (che corrisponde **moooolto** approssimativamente a mettere zoom 90%), ma mi viene da chiedermi a priori perché esista questa impostazione. Probabilmente però questo non è né il luogo né il momento per discutere di questa cosa (semicit.).

**Comment by mexicat** [comment]
L'impostazione esiste perché su Vector con le impostazioni di default il font è troppo piccolo nonostante i 16px. Su Minerva non avrebbe mai dovuto esserci ma nessuno se ne è ricordato quando abbiamo attivato la versione mobile, si può togliere anche da lì.

**Comment by flavio-a** [comment]
@mexicat sicuro non rompa dei layout? Perché ormai sono stati tutti adattati al font 17px, quindi forse rimpicciolendolo ci sono dei problemi. È anche vero che di solito la cosa problematica è ingrandire il font, ma comunque ormai possiamo lasciarlo anche a Minerva

**Comment by lucas992x** [comment]
Ho appena provato Timeless con questa modifica e va decisamente molto meglio. Forse si può rimpicciolire il testo ancora un pochino, ma veramente di poco, già così mi sembra più o meno allo stesso livello di Vector.

**Comment by mexicat** [comment]
> @mexicat sicuro non rompa dei layout? Perché ormai sono stati tutti adattati al font 17px, quindi forse rimpicciolendolo ci sono dei problemi. È anche vero che di solito la cosa problematica è ingrandire il font, ma comunque ormai possiamo lasciarlo anche a Minerva

Non vedo controindicazioni nel rimpicciolire il font su Minerva (al contrario dell'ingrandirlo che sarebbe problematico), mentre vedo il grosso vantaggio che ci sta più roba nello schermo... Per quanto può valere ho fatto una breve prova coi dev tools togliendo la definizione sul simulatore mobile e non mi sembrava si fosse rotto niente.

**Comment by flavio-a** [comment]
> Non vedo controindicazioni nel rimpicciolire il font su Minerva (al contrario dell'ingrandirlo che sarebbe problematico), mentre vedo il grosso vantaggio che ci sta più roba nello schermo... Per quanto può valere ho fatto una breve prova coi dev tools togliendo la definizione sul simulatore mobile e non mi sembrava si fosse rotto niente.

Ok, allora provo a toglierla e vediamo. La lascio solo su Vector.

> Forse si può rimpicciolire il testo ancora un pochino, ma veramente di poco
Posso provare a calare ancora, ma di base preferirei non toccare i default. E poi il testo deve rimanere leggibile comodamente

**Comment by Cruifer** [comment]
Posto che sono da tablet e su safari, questa cosa è un po’ brutta
![6F6DFDC6-64D7-45E0-9B1F-DE4235B8E1AF](https://user-images.githubusercontent.com/38588039/95622576-12091000-0a74-11eb-9548-99ee7d22387d.jpeg)

**Comment by lucas992x** [comment]
Ho sistemato facendolo diventare un semplice elenco, che mi sembra anche più bello e intuitivo, e ne ho approfittato per aggiornare alcune cose qua e là con le nuove classi (`white-bg` e `white-text`).

**Comment by lucas992x** [comment]
Ho notato ora che quando si edita con Timeless e si visualizza l'anteprima non vengono mostrate le categorie e le altre lingue, cosa che invece avviene usando Vector. Non è un grosso problema, ma se si trovasse una soluzione sarebbe buona cosa.
EDIT ho appena notato che quando lo schermo è inferiore a `xl` si vedono le categorie.

**Comment by Cruifer** [comment]
sicuro che non sia un problema tuo? io vedo tutto correttamente anche da `xl`
![image](https://user-images.githubusercontent.com/38588039/95874376-1fbede00-0d71-11eb-98f9-bb1968fbd739.png)

**Comment by lucas992x** [comment]
Credo tu abbia attivato "Ricarica la pagina per mostrare l'anteprima" o qualcosa del genere, giusto?

**Comment by Cruifer** [comment]
boh, ho "Mostra anteprime senza ricaricare la pagina" non spuntato, ma non ricordo di averlo mai toccato

**Comment by lucas992x** [comment]
Ecco, io ce l'ho abilitato e con Timeless non vedo categorie e lingue, mentre con Vector sì

**Comment by CiaobyDany** [comment]
Allora, numeri rilevanti:

- Da 850 pixel in giù tutti i menù sono rappresentati da icone e viene rimosso il margine laterale dal content
- Da 1100 pixel in su appare la sidebar di sinistra
- Da 1340 pixel in su appare la sidebar di destra

Una soluzione magari poco elegante ma efficace per la larghezza non interpretata correttamente e per gli elementi larghi che strabordano potrebbe essere aumentare il limite di comparsa da 1340 pixel a... Boh, qualcuno con schermi larghi faccia delle prove se con più spazio a disposizione funziona decentemente e/o se potrebbe risolvere mettere un numero ridicolmente alto in modo che non appaia mai.

Pro: risolve i problemi della larghezza rendendola quasi stabile per il pubblico
Contro: la sidebar è solo drop down che è leggermente scomodo, ma in ottica mobile-first potrebbe essere un compromesso accettabile per liberarci di Minerva.

**Comment by lucas992x** [comment]
Io invece stavo pensando che si potrebbe provare a restringere un pochino le due sidebar, se qualcuno riuscisse a fare delle prove e inviare screen potremmo ragionarci su.

**Comment by flavio-a** [comment]
Non riesci a tagliare più di tanto senza che il testo non vada su due righe, e dopo fa schifo:
![2020-11-15-123420_1920x1028_scrot](https://user-images.githubusercontent.com/11007745/99183819-fd88f900-273e-11eb-903a-385ff0afc76a.png)
Senza andare su due righe si rubano circa 2em a sinistra e 3 a destra: 5em in totale mi sembrano abbastanza pochi da non valere davvero la pena, ma ditemi voi.

Un'altra idea che è venuta in mente è che potremmo usare breakpoint diversi per le diverse skin. I breakpoint che usiamo adesso sono quelli di Bootstrap, che sono pensati per essere a schermo intero. Noi invece abbiamo tutto dentro un contenitore che è più piccolo della dimensione reale della finestra, e il problema è che la dimensione del contenitore rispetto alla finestra cambia a seconda della skin. Se utilizzassimo breakpoint diversi per ogni skin potremmo adattarli alla dimensione del contenitore di quella skin, e ottenere circa lo stesso effetto su tutte le skin. Ora
1) non so quanto abbia davvero senso questa idea
2) non so quanto sia realizzabile tecnicamente (abbiamo dei CSS diversi per ogni skin? Perché se MW non ce li dà non abbiamo molte opzioni)
3) non so quanto sia complicato farla retrocompatibile: dover rifare tutti i template del sito per cambiare i breakpoint NON è un'opzione.

Volevo i pareri di @mexicat e @davla su questa idea.

**Comment by CiaobyDany** [comment]
@flavio-a Io ero rimasto che questa fosse la soluzione definitiva tbh, ma che fosse complessa da implementare. Per quanto riguarda la retrocompatibilità non credo sia un grosso problema, basta controllare agli attuali breakpoint quanto valga il contenitore su Vector (lg e xl, visto che da md in giù partiamo dal presupposto che non si debba usare Vector ma Minerva/Timeless ed entrambe non dovrebbero avere le sidebar) e riadattare i breakpoint su quelle misure. Il più è appunto capire se sia possibile fare i breakpoint sul contenitore (e come), poi mi sembra easy.

**Comment by flavio-a** [comment]
La mia idea appunto sarebbe di non fare i breakpoint direttamente sul contenitore (perché non si può) ma "fare finta" che sia così usando dei breakpoint sullo schermo ma a valori diversi per ogni skin, dato che per ogni skin una certa dimensione dello schermo corrisponde ad una certa dimensione del contenitore. Per fare questo però bisogna vedere se MediaWiki ha dei CSS diversi per ogni skin (quelli tra desktop e mobile non contano perché lì appunto non dipende dalla skin, ma dall'essre desktop o mobile)

**Comment by Cruifer** [comment]
@flavio-a Dagli esperimenti che ho fatto per umbrawiki ti posso dire che Mediawiki:Vector.css e Mediawiki:Timeless.css esistono e vengono caricati su desktop. Non su mobile però come avevamo visto, se ti ricordi. C'è da capire se la cosa funziona su pcw o meno, quindi aspettiamo i pareri più autorevoli di gika e dedalo

**Comment by flavio-a** [comment]
@Cruifer c'è da dire che mobile mi preoccupa meno perché mi immagino venga caricata solo da telefoni/tablet, dove sia Minerva che Timeless sono a schermo intero e quindi hanno gli stessi breakpoint

**Comment by flavio-a** [comment]
## tl;dr
Tutto sto papiro perché ho fatto un po' di prove e preferisco scrivere da qualche parte i risultati, ma basta leggere questa prima sezione.
Da `md` in giù non ci sono problemi perché Timeless non ha sidebar, quindi è come Minerva.
La tabella mostra la dimensione minima che il contenuto raggiunge a quel breakpoint per le varie skin. Timeless- è la Timeless con le sidebar ristrette come consigliava Luca; Timeless1 con entrambe le sidebar sempre a sinsitra come proponeva Dany.
|                  | `xl`      | `lg`     |
|---------------|----------|---------|
| Vector       | `1013` | `805` |
| Timeless   | `853`   | `856` |
| Timeless-  | `929`   | `872` |
| Timeless1 | `956`   | `856` |

I numeri di Vector sono quelli su cui abbiamo calibrato i template, quindi Timeless dovrebbe avere tutti i numeri maggiori o uguali a quelli di Vector nella stessa casella per essere sicuri che tutto funzioni bene; più sono piccoli più si rompe roba.

## Numeri per tutti
Un po' di numeri perché so che vi piacciono tanto. `cont` sarà la dimensione del container (quella in cui sta il nostro contenuto), `scr` quello dello schermo (rispetto alla quale vengono calcolati i breakpoints). Poi faccio considerazioni solo sui breakpoints `xl` ed `lg`, dato che da `md` in giù Timeless non ha sidebar e quindi il container è largo come lo schermo (e dunque non ci sono problemi).
Questi numeri possono anche essere utili per eventualmente cambiare i valori dei breakpoint, ammesso che si riesca.

### Vector
Vale sempre `cont = scr - 187px`, che è poi la larghezza della sidebar. Questo vuol dire che la larghezza minima del container è `1013px` in `xl` e `805px` in `lg`. Questi numeri sono importanti perché sono quelli su cui abbiamo calibrato i template prima: i nostri template sono fatti per vedersi bene in breakpoint `xl` se hanno almeno `1013px` di larghezza.

### Timeless
Qua la cosa è più complicata perché dipende da quali sidebar ci sono. Con entrambe le sidebar (fino a `1340px` di schermo) vale `cont = scr - 487px`, quindi si arriva al minimo di `853px` __ancora a breakpoint `xl`__. E questa è la causa di ogni male, perché parliamo di _un sacco_ di spazio in meno rispetto ai `1013px` di Vector.
Da 1340px a 1100px di schermo c'è solo una sidebar, quindi vale `cont = scr - 244px`, quindi minimo nel breakpoint `xl` a `1200px` di schermo per una larghezza di `956px`, che è più piccolo dei `1013px` di Vector ma non di troppo.
In breakpoint `lg` invece abbiamo larghezza minima di Timeless a `1100px` di schermo, che è il minimo a cui resta la sidebar di sinistra, per una larghezza del content di `856px`, che è in realtà di più degli `805px` minimi di Vector a breakpoint `lg`, quindi in teoria qua non dovremmo avere problemi.

### Timeless con sidebar più piccole (Timeless-)
Dietro proposta di Luca ho provato a rimpicciolire le sidebar di quello che si poteva per vedere cosa salta fuori. Ho guardato solo `xl` perché appunto `lg` dovrebbe essere già a posto.
Fino a `1340px`: `cont = scr - 411px`, minimo `929px`
Fino a `1100px`: `cont = scr - 228px`, minimo `972px` (perché siamo in `xl`, quindi `scr >= 1200px`)

### Timeless con una sola sidebar (Timeless1)
Un'altra soluzione proposta da Dany è quella di spostare la sidebar di destra sotto quella di sinistra prima. Questo vorrebbe dire usare la formula fino a `1100px` anche sopra i `1340px`: il minimo di Timeless diventerebbe infatti `956px`, che non è troppo più piccolo di `1013px`. Con un po' di fortuna dovrebbe ancora funzionare tutto. O comunque dovrebbero rompersi poche cose. Se restringiamo anche la sidebar andiamo addirittura a `972px`.
Avere le categorie in fondo alla sidebar non è comodissimo, ma tanto chi è che le usa davvero?

**Comment by CiaobyDany** [comment]
@flavio-a Giusto per precisare, io dicevo di mettere la sidebar di destra collassata (quindi come avviene ora sotto i 1100) in dropdown. Ovviamente se si potesse spostare a sinistra sarebbe ancora meglio, ma immagino che sia tecnicamente più complesso da realizzare. Alla fine tutto dipende da cosa sia fattibile nella pratica, quindi deciderai tu lel.

**Comment by Cruifer** [comment]
@flavio-a Nella tabella in cella Timeless-lg non dovrebbe essere 956? Perché non torna col calcolo sotto. In ogni caso, non ci ho capito molto, quindi buona fortuna

**Comment by flavio-a** [comment]
> Giusto per precisare, io dicevo di mettere la sidebar di destra collassata (quindi come avviene ora sotto i 1100) in dropdown. Ovviamente se si potesse spostare a sinistra sarebbe ancora meglio, ma immagino che sia tecnicamente più complesso da realizzare. Alla fine tutto dipende da cosa sia fattibile nella pratica, quindi deciderai tu lel.

In realtà la sidebar di destra finisce sotto a quella di sinistra tra `1340px` e `1100px` di default per Timeless, quindi è molto più facile fare così che non collassarla mentre quella di sinistra è ancora visibile (perché appunto basta cambiare il breakpoint a cui Timeless la sposta invece di dover cambiare tutto per far collassare le cose) LOL

> Nella tabella in cella Timeless-lg non dovrebbe essere 956? Perché non torna col calcolo sotto. In ogni caso, non ci ho capito molto, quindi buona fortuna

No, i numeri sono giusti così. Comunque il tl;dr è che dobbiamo cambiare qualcosa in modo che i numeri di Timeless in quella tabella siano più dei numeri di Vector della stessa colonna.

Un'altra soluzione un po' stupida che mi è appena venuta in mente è di far sparire `xl` su Timeless e rendere `lg` tutti gli schermi grossi. Anche questo dovrebbe risolvere i problemi; non sono però convintissimo perché forse `lg` su schermi larghi fa un po' schifo (tipo box troppo enormi).

## Prove da fare
* Far sparire `xl` e vedere come si comporta `lg` su schermi enormi
* Restringere e spostare le sidebar e vedere se ci sono comunque problemi ad `xl`
* Ricalcolare le dimensioni dei breakpoints e vedere cosa esce fuori

**Comment by CiaobyDany** [comment]
@flavio-a Scusate, ho sempre visto i contenuti della sidebar di destra collassati a destra quando spariscono le sidebar e ho dato per scontato che facesse così anche quando di sidebar ce n'era una. E invece no, sono solo scemo. Molto bene.

**Comment by mexicat** [comment]
@CiaobyDany mi devo leggere tutto per bene, comunque nel frattempo date un’occhiata a questo snippet ufficiale per tenere una sola barra laterale: https://www.mediawiki.org/wiki/Skin:Timeless#One-sided_navigation_menu

**Comment by flavio-a** [comment]
> date un’occhiata a questo snippet ufficiale per tenere una sola barra laterale: https://www.mediawiki.org/wiki/Skin:Timeless#One-sided_navigation_menu

Questo snippet è molto interessante, è essenzialmente la cosa che ci serve. Ho fatto qualche prova e parzialmente funziona (le pagine Grigiosfera e Mosse errate dei giochi si vedono bene, e Grigiosfera anche con abbastanza margine), anche se ci sono ancora problemi ([pagina dell' ndex](https://wiki.pokemoncentral.it/Elenco_Pok%C3%A9mon_secondo_il_Pok%C3%A9dex_Nazionale), ma forse questa ha senso sistemarla in generale perché è molto tirata sui breakpoint xl ed lg).
Pensavo comunque di metterlo su MediaWiki:Timeless.css come suggeriscono lì così lo provate anche voi.

**Comment by lucas992x** [comment]
Confermo che quella pagina è da sistemare, forse hai anche tu questo stesso problema che ho io:
![scr](https://user-images.githubusercontent.com/38510975/99587241-19172c80-29e9-11eb-8062-dfc8d33c1ec2.png)

Per il resto non mi dispiace Timeless con sidebar singola, dovrebbe risolvere buona parte dei problemi che abbiamo con questa skin. Sarà solo un pochino più scomoda per noi che usiamo i vari comandi delle sidebar, ma non lo trovo problematico.

**Comment by flavio-a** [comment]
> Confermo che quella pagina è da sistemare, forse hai anche tu questo stesso problema che ho io

@lucas992x sì, stesso problema ma lì più che colpa di Timeless credo sia colpa mia che ho preso le larghezze al millimetro quando ho fatto il template. Però avevo un motivo sensato, volevo tenere 3 Pokémon per riga su xl. Bisognerà lavorarci, ma non credo abbia senso discuterne ulteriormente qui, è un problema di quell'elenco.

> Sarà solo un pochino più scomoda per noi che usiamo i vari comandi delle sidebar, ma non lo trovo problematico.

Come ho scritto su Telegram si può recuperare la seconda sidebar per schermi abbastanza larghi (`1500px` dovrebbe andare, ma per sicurezza possiamo usare `1600px` come breakpoint e siamo a posto) e comunque evitare problemi. Non ho capito però se è una cosa che vogliamo o no, Dany diceva probabilmente sì perché schermi troppo larghi potrebbero causare effetti strani, e la seconda sidebar aiuterebbe ad evitarlo; inoltre editando da desktop avremmo la doppia sidebar che è comoda. Se non ci sono contrari faccio questa modifica.

**Comment by lucas992x** [comment]
Segnalo che su schermi 15.6" (nel mio caso 1366×768 ma non so se faccia così anche con altre risoluzioni) le categorie elencano le pagine su 3 colonne in Vector ma solo 2 in Timeless, si riesce a sistemare questa cosa?
Inoltre la sidebar di sinistra è parecchio lunga, si riesce ad accorciarla almeno un pochino?

![scr1](https://user-images.githubusercontent.com/38510975/99976867-41fe3f80-2da4-11eb-9f12-6a06f1be6b81.png)
![scr2](https://user-images.githubusercontent.com/38510975/99976870-4296d600-2da4-11eb-89a8-eae0d808c459.png)

**Comment by flavio-a** [comment]
> Inoltre la sidebar di sinistra è parecchio lunga, si riesce ad accorciarla almeno un pochino?

Come vorresti farlo?

> le categorie elencano le pagine su 3 colonne in Vector ma solo 2 in Timeless

È veramente un problema? Cioè, probabilmente si può sistemare, ma se dobbiamo rifare mezza Timeless per essere uguale a Vector anche no. In generale non state a fare paragoni di tutto con Vector. Sulla larghezza dello schermo è una necessità perché abbiamo tutte le cose responsive tarate su quelle, ma per il resto Timeless non è Vector.

Piuttosto devo ricordarmi di sistemare i link social che non hanno le icone di fianco.

**Comment by lucas992x** [comment]
1) Vedo che c'è un discreto spazio fra i 3 pezzi in cui è divisa la sidebar, tra le cose che si potrebbero provare mi viene in mente quella di mettere tutto in un pezzo unico e di diminuire un pochino lo spazio fra una sezione e l'altra.
2) Non è un problema, è più un fastidio, quindi se si riesce a sistemare con poco sforzo bene altrimenti fa nulla.

**Comment by flavio-a** [comment]
> Non è un problema, è più un fastidio, quindi se si riesce a sistemare con poco sforzo bene altrimenti fa nulla.

In generale qualsiasi modifica fatta alla skin base è potenzialmente uno sforzo non trascurabile perché potrebbe rompersi in futuri aggiornamenti, quindi l'idea è di tenerle al minimo indispensabile. Se ritenete questa cosa importante ci posso lavorare, ma mi sembra di capire che non sia così.

Idem per la sidebar: quanto è importante ridurla? Posto che unire davvero tutti i pezzi non si riesce, quindi al massimo possiamo farlo "per finta" dal css, e ammesso che ci si riesca questo sembra abbastanza una rottura da fare bene. Si può però provare a ridurre sia lo spazio tra sezioni nello stesso blocco che lo spazio tra blocchi, e questo sembra ragionevole da fare.

**Comment by Cruifer** [comment]
Non è un vero problema e se non si può risolvere pazienza, ma solo a me triggera tantissimo che cliccando sul logo in alto a sx non si venga reindirizzati alla home? tocca per forza cliccare il link piccolo sotto, mentre il logo sarebbe molto più comodo

**Comment by CiaobyDany** [comment]
@Cruifer No, non triggera solo te

**Comment by flavio-a** [comment]
Ehm... a me in realtà lo fa 😅

**Comment by lucas992x** [comment]
Anche a me reindirizza correttamente alla Home

**Comment by CiaobyDany** [comment]
@lucas992x Allora, ho fatto un po' di tentativi. Da Firefox Nightly, Firefox, Edge e Chrome NON funziona, mentre su Vivaldi sì (????). In compenso, ho avuto l'illuminazione e ho notato che se diminuisco lo zoom per far apparire anche la sidebar di destra, fa il link correttamente. Quindi mi viene da pensare che Flavio e Luca abbiano schermi da pro gamer mentre io e Crusca abbiamo le Poveraccy Version a 1366x768 e con la sola sidebar a sinistra il link non appare sul logo (tranne che su Vivaldi che dovrebbe funzionare come Chrome in teoria ma con i browser non ci si annoia mai). Ciò detto, considerando che lentamente la risoluzione 1366x768 immagino che stia andando a morire e che mediamente quella skin passerà da sperimentale a stabile tra non meno di tre anni e che potrebbe diventare la default dopo almeno altri due, o con queste indicazioni riuscite a trovare easy come risolverla, oppure non mi sembra più così problematica come situazione.

**Comment by lucas992x** [comment]
Effettivamente provando con lo strumento responsive noto che fino a 1500 px di larghezza l'immagine è priva di link, mentre da 1501 px in poi linka alla Home (io ho uno schermo FHD quindi non me n'ero mai accorto).
